---
# - name: Include OS-specific variables "{{ ansible_distribution }}-{{ ansible_distribution_version }}.
#   include_vars: "{{ ansible_os_family }}.yml"
#   when: ansible_distribution != 'Ubuntu' or ansible_distribution != 'Fedora'

# - name: Define java_packages.
#   set_fact:
#     java_packages: "{{ __java_packages | list }}"
#   when: java_packages is not defined

# # Setup/install tasks.
# - include: setup-RedHat.yml
#   when: ansible_os_family == 'RedHat'
#   static: no

# # Environment setup.
# - name: Set JAVA_HOME if configured.
#   template:
#     src: java_home.sh.j2
#     dest: /etc/profile.d/java_home.sh
#     mode: 0644
#   when: java_home is defined and java_home != ''

# - debug:
#     msg: "System {{ ansible_distribution }} has uuid {{ ansible_distribution_version }}"
- name: Install the package "python-software-properties"
  apt:
    name: python-software-properties
    state: present

- name: Check python version
  shell: python --version
  register: python_version

- debug: var=python_version

