---
# - name: Include OS-specific variables "{{ ansible_distribution }}-{{ ansible_distribution_version }}.
#   include_vars: "{{ ansible_os_family }}.yml"
#   when: ansible_distribution != 'Ubuntu' or ansible_distribution != 'Fedora'

# - name: Define java_packages.
#   set_fact:
#     java_packages: "{{ __java_packages | list }}"
#   when: java_packages is not defined

# # Setup/install tasks.
# - include: setup-RedHat.yml
#   when: ansible_os_family == 'RedHat'
#   static: no

# # Environment setup.
# - name: Set JAVA_HOME if configured.
#   template:
#     src: java_home.sh.j2
#     dest: /etc/profile.d/java_home.sh
#     mode: 0644
#   when: java_home is defined and java_home != ''

# - debug:
#     msg: "System {{ ansible_distribution }} has uuid {{ ansible_distribution_version }}"
# - group:
#     name: hadoop
#     state: present

# - name: Adding user  - {{ user }}  
#   user: name={{ user }}
#         group={{ group }}
#         shell=/bin/bash
#         password=${password}
#         groups=sudo
#         append=yes
#         generate_ssh_key=yes
#         ssh_key_bits=2048
#         ssh_key_file=.ssh/id_rsa

# - name: Set authorized key took from file
#   authorized_key: user=hduser key="{{ lookup('file', './files/authorized_keys.hduser.pub') }}"


- user:
    name: hduser
    comment: "Hadoop User"
    shell: /bin/bash
    groups: sudo
    append: yes
    generate_ssh_key: yes
    ## run command 'mkpasswd --method=sha-512' to create your own encrypted password ##
    password: $6$FJCD6DfRWieE$XEb5U924ydsk8JW0bXhE1VWx5xs3hfQR/yla70Pi/GVdA37XJu36gpW2q3qm7DKJ9hGGuy.RYe6V3XvAa2cN7/
    # ssh_key_type: id_rsa
# upload ssh key
- authorized_key:
    user: hduser
    state: present
    manage_dir: yes
    key: "{{ lookup('file', '/home/prem/.ssh/id_rsa.pub') }}"
# configure ssh server
- template:
    src: ./files/ssh-setup.j2
    dest: /etc/ssh/sshd_config
    owner: root
    mode: '0600'
    validate: /usr/sbin/sshd -t -f %s
    backup: yes
# restart sshd
- service:
    name: ssh
    state: restarted

