---
# Set java_packages if you would like to use a different version than the
# default (OpenJDK 1.7).
# java_packages: []

user: 'hduser'
group: 'hadoop'


sshd_use_pam: 'no'
sshd_password_authentication: 'no'
sshd_challenge_response_authentication: 'no'
sshd_permitroot_login: 'no'